steps:
- name: gcr.io/cloud-builders/docker
  id: 'build-container-image'
  args:
    - 'build'
    - '--no-cache'
    - '-t'
    - 'gcr.io/$_REPO_PROJ_ID/rebred:latest'
    - '.'
  waitFor: ['-']

- name: gcr.io/cloud-builders/docker
  id: 'push-container-image'
  args:
    - 'push'
    - 'gcr.io/$_REPO_PROJ_ID/rebred:latest'
  waitFor: ['build-container-image']

- name: gcr.io/cloud-builders/gcloud-slim
  id: 'deploy'
  args:
    - 'run'
    - 'services'
    - 'update'
    - 'rebred'
    - '--platform=managed'
    - '--image=gcr.io/$_REPO_PROJ_ID/rebred:latest'
    - '--region=us-central1'
    - '--set-env-vars=${_ENV1},${_ENV2}'
    - '--quiet'
  waitFor: ['push-container-image']

- name: gcr.io/cloud-builders/gcloud-slim
  id: 'redirect-traffic'
  args:
    - 'run'
    - 'services'
    - 'update-traffic'
    - 'rebred'
    ' --to-latest'
  waitFor: ['deploy']
images:
  - 'gcr.io/$_REPO_PROJ_ID/rebred'